In [2]:
import pandas as pd
import numpy as np

## Total withdrawn IPO

In [3]:
df = pd.read_html("https://iposcoop.com/ipos-recently-filed")
# print(df[0].columns)
df[0].columns = [columns.replace(" ", "_") for columns in df[0].columns]
# len(df[0].query('Expected_To_Trade == "Withdrawn"'))
withdrawed_ipo = df[0].query('Expected_To_Trade == "Withdrawn"')
withdrawed_ipo.head()
# for x in df:
#     if x["Expected To Trade"] == "Withdrawn":
#         withdrawn_ipo = x
#         break

,File_Date,Company,Symbol,Managers,Shares_(millions),Price_Low,Price_High,Est_$_Vol_(millions),Expected_To_Trade,SCOOP_Rating
0,2026-09-25,Holtec Nuclear (Withdrawn),HNUC,J.P.Morgan/Guggenheim Securities/Goldman Sachs...,50.00,$15.00,$18.00,$825.00,Withdrawn,S/O
18,2026-09-18,Rise Smart Group (Withdrawn),RSHL,American Trust Investment Services/Prime Numbe...,1.80,$4.00,$4.00,$7.20,Withdrawn,S/O
21,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,$4.00,$5.00,$16.88,Withdrawn,S/O
33,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,$4.50,$5.50,$22.00,Withdrawn,S/O
39,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O

In [4]:
import re
def classify_company(name: str) -> str:
    if not isinstance(name, str):
        return "Other"
    if re.search(r"\bTechnologies\b", name):
        return "Technologies"
    elif re.search(r"\b(Acquisition Corp|Acquisition Corporation|Corp)\b", name):
        return "Acquisition Corp"
    elif re.search(r"\b(Inc|Incorporated)\b", name):
        return "Inc."
    elif re.search(r"\bGroup\b", name):
        return "Group"
    elif re.search(r"\b(Ltd|Limited)\b", name):
        return "Limited"
    elif re.search(r"\b(Holdings|Holding)\b", name):
        return "Holdings"
    else:
        return "Other"

# Apply to your DataFrame
withdrawed_ipo["Company Type"] = withdrawed_ipo["Company"].apply(classify_company)
withdrawed_ipo.head()

,File_Date,Company,Symbol,Managers,Shares_(millions),Price_Low,Price_High,Est_$_Vol_(millions),Expected_To_Trade,SCOOP_Rating,Company Type
0,2026-09-25,Holtec Nuclear (Withdrawn),HNUC,J.P.Morgan/Guggenheim Securities/Goldman Sachs...,50.00,$15.00,$18.00,$825.00,Withdrawn,S/O,Other
18,2026-09-18,Rise Smart Group (Withdrawn),RSHL,American Trust Investment Services/Prime Numbe...,1.80,$4.00,$4.00,$7.20,Withdrawn,S/O,Group
21,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,$4.00,$5.00,$16.88,Withdrawn,S/O,Group
33,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,$4.50,$5.50,$22.00,Withdrawn,S/O,Limited
39,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O,Technologies

In [5]:
def parse_price(val):
    if pd.isna(val) or str(val).strip() in ["-", ""]:
        return np.nan
    clean_val = re.sub(r"[^\d.]", "", str(val))
    try:
        return float(clean_val)
    except ValueError:
        return np.nan
withdrawed_ipo["Price_Low"] = withdrawed_ipo["Price_Low"].apply(parse_price)
withdrawed_ipo["Price_High"] = withdrawed_ipo["Price_High"].apply(parse_price)
withdrawed_ipo["Avg_price"] = withdrawed_ipo[["Price_Low", "Price_High"]].mean(axis=1)
withdrawed_ipo.head()

,File_Date,Company,Symbol,Managers,Shares_(millions),Price_Low,Price_High,Est_$_Vol_(millions),Expected_To_Trade,SCOOP_Rating,Company Type,Avg_price
0,2026-09-25,Holtec Nuclear (Withdrawn),HNUC,J.P.Morgan/Guggenheim Securities/Goldman Sachs...,50.00,15.0,18.0,$825.00,Withdrawn,S/O,Other,16.5
18,2026-09-18,Rise Smart Group (Withdrawn),RSHL,American Trust Investment Services/Prime Numbe...,1.80,4.0,4.0,$7.20,Withdrawn,S/O,Group,4.0
21,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,$16.88,Withdrawn,S/O,Group,4.5
33,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,$22.00,Withdrawn,S/O,Limited,5.0
39,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O,Technologies,NaN

In [6]:
withdrawed_ipo["Est_$_Vol_(millions)"] = withdrawed_ipo["Est_$_Vol_(millions)"].apply(parse_price)
withdrawed_ipo.head()

,File_Date,Company,Symbol,Managers,Shares_(millions),Price_Low,Price_High,Est_$_Vol_(millions),Expected_To_Trade,SCOOP_Rating,Company Type,Avg_price
0,2026-09-25,Holtec Nuclear (Withdrawn),HNUC,J.P.Morgan/Guggenheim Securities/Goldman Sachs...,50.00,15.0,18.0,825.00,Withdrawn,S/O,Other,16.5
18,2026-09-18,Rise Smart Group (Withdrawn),RSHL,American Trust Investment Services/Prime Numbe...,1.80,4.0,4.0,7.20,Withdrawn,S/O,Group,4.0
21,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,16.88,Withdrawn,S/O,Group,4.5
33,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,22.00,Withdrawn,S/O,Limited,5.0
39,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Technologies,NaN

In [7]:
# shares_offered = withdrawed_ipo["Shares_(millions)"] * withdrawed_ipo["Est_$_Vol_(millions)"]
withdrawed_ipo["Shares_offered_value"] = withdrawed_ipo["Shares_(millions)"] * withdrawed_ipo["Avg_price"]
withdrawed_ipo["Shares_offered_value"] = withdrawed_ipo["Shares_offered_value"].fillna(withdrawed_ipo["Est_$_Vol_(millions)"])
withdrawed_ipo.head()

,File_Date,Company,Symbol,Managers,Shares_(millions),Price_Low,Price_High,Est_$_Vol_(millions),Expected_To_Trade,SCOOP_Rating,Company Type,Avg_price,Shares_offered_value
0,2026-09-25,Holtec Nuclear (Withdrawn),HNUC,J.P.Morgan/Guggenheim Securities/Goldman Sachs...,50.00,15.0,18.0,825.00,Withdrawn,S/O,Other,16.5,825.000
18,2026-09-18,Rise Smart Group (Withdrawn),RSHL,American Trust Investment Services/Prime Numbe...,1.80,4.0,4.0,7.20,Withdrawn,S/O,Group,4.0,7.200
21,2026-09-17,C2 Capital Group (Withdrawn),CCLV,Dominari Securities,3.75,4.0,5.0,16.88,Withdrawn,S/O,Group,4.5,16.875
33,2026-09-15,OTSAW Ltd. (Withdrawn),OTSA,Aegis Capital,4.40,4.5,5.5,22.00,Withdrawn,S/O,Limited,5.0,22.000
39,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,100.00,Withdrawn,S/O,Technologies,NaN,100.000

In [8]:
withdrawed_ipo.groupby("Company Type")["Shares_offered_value"].sum().sort_values(ascending=False)

Company Type
Other               1115.4450
Acquisition Corp     499.9850
Inc.                 351.0000
Holdings             311.6575
Limited              219.2500
Technologies         184.9000
Group                 56.5750
Name: Shares_offered_value, dtype: float64

In [26]:
url = "https://www.iposcoop.com/2025-pricings/"
tables = pd.read_html(url)
ipos_df = tables[0]
ipos_df['Offer Date'] = pd.to_datetime(ipos_df['Offer Date'], errors='coerce')

filtered_ipos = ipos_df[(ipos_df['Offer Date'] < '2025-09-01') & (ipos_df['Return'] != '0.00%')]
filtered_ipos

,Company,Symbol,Industry,Offer Date,Shares (millions),Offer Price,1st Day Close,Current Price,Return,SCOOP Rating
68,"Picard Medical, Inc.",PMI,Health Care,2025-08-29,4.3,$4.00,$4.59,$1.68,-58.00%,S/O
69,GrowHub Limited (The),TGHL,Technology,2025-08-28,3.7,$4.00,$3.38,$0.40,-90.00%,S/O
70,TryHard Holdings Limited,THH,Consumer Services,2025-08-28,1.5,$4.00,$6.02,$29.47,636.75%,S/O
71,Curanex Pharmaceuticals,CURX,Health Care,2025-08-26,3.8,$4.00,$4.02,$0.37,-90.75%,S/O
72,"Cantor Equity Partners IV, Inc. (Stock-Only SPAC)",CEPF,Blank Check,2025-08-21,40.0,$10.00,$10.12,$10.12,1.20%,S/O
...,...,...,...,...,...,...,...,...,...,...
226,Mint Inc. Ltd.,MIMI,Other,2025-01-10,1.8,$4.00,$4.11,$5.30,32.50%,S/O
227,3 E Network Technology Group Limited,MASK,Technology,2025-01-08,1.3,$4.00,$3.25,$2.75,-31.25%,S/O
228,"Cantor Equity Partners I, Inc. (Stock-Only SPAC)",CEPO,Blank Check,2025-01-07,20.0,$10.00,$10.05,$10.10,1.00%,S/O
229,Zhengye Biotechnology Holding Limited,ZYBT,Health Care,2025-01-07,1.5,$4.00,$4.86,$4.22,5.50%,S/O
230,INLIF Ltd.,INLF,Industrials,2025-01-02,2.0,$4.00,$4.45,$1.96,-51.00%,S/O

In [35]:
import yfinance as yf
tickers = filtered_ipos['Symbol'].dropna().astype(str).str.strip().tolist()

# 3. Data Download via yfinance
data = yf.download(tickers, start="2025-01-01", end="2026-09-12", group_by='ticker')
data

[*******               14%                       ]  21 of 146 completed$SKBL: possibly delisted; no timezone found
[********              16%                       ]  23 of 146 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WGRX"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CEPT"}}}
[**********            21%                       ]  30 of 146 completed$WGRX: possibly delisted; no timezone found
[************          25%                       ]  36 of 146 completed$CEPT: possibly delisted; no timezone found
[*************         27%                       ]  40 of 146 completed$SDM: possibly delisted; no timezone found
[***************       32%                       ]  46 of 146 completed$MCTR: possibly delisted; no timezone found
[****************      34%                       ]  49 of 146 completed$PTNM: possibly delisted; no timezone found
[**********************45%                       ]  66 of 146 completed$MTSR: possibly delisted; no timezone found
[**********************47%                       ]  69 of 146 completed$EMPG: possibly delisted; no timezone found
[**********************48%                       ]  70 of 146 completed$AGH: possibly delisted; no timezone found
[**********************57%**                     ]  83 of 146 completed$AHL: possibly delisted; no timezone found
[**********************58%***                    ]  85 of 146 completed$MJID: possibly delisted; no timezone found
[**********************62%*****                  ]  91 of 146 completed$CAEP: possibly delisted; no timezone found
[**********************64%******                 ]  93 of 146 completed$DLXY: possibly delisted; no price data found  (1d 2025-01-01 -> 2026-09-12)
[**********************75%***********            ]  110 of 146 completed$EPWK: possibly delisted; no timezone found
[**********************82%**************         ]  120 of 146 completed$TBH: possibly delisted; no timezone found
[*********************100%***********************]  145 of 146 completed

15 Failed downloads:
['SKBL', 'WGRX', 'CEPT', 'SDM', 'MCTR', 'PTNM', 'MTSR', 'EMPG', 'AGH', 'AHL', 'MJID', 'CAEP', 'EPWK', 'TBH']: possibly delisted; no timezone found
['DLXY']: possibly delisted; no price data found  (1d 2025-01-01 -> 2026-09-12)

Ticker       MNTN                                    CIGL                    \
Price        Open    High     Low  Close     Volume  Open  High   Low Close
Date
2025-01-02    NaN     NaN     NaN    NaN        NaN   NaN   NaN   NaN   NaN
2025-01-03    NaN     NaN     NaN    NaN        NaN   NaN   NaN   NaN   NaN
2025-01-06    NaN     NaN     NaN    NaN        NaN   NaN   NaN   NaN   NaN
2025-01-07    NaN     NaN     NaN    NaN        NaN   NaN   NaN   NaN   NaN
2025-01-08    NaN     NaN     NaN    NaN        NaN   NaN   NaN   NaN   NaN
...           ...     ...     ...    ...        ...   ...   ...   ...   ...
2026-09-04  13.32  13.320  12.810  12.95   445500.0  0.40  0.41  0.40  0.41
2026-09-08  12.86  13.070  12.350  12.81   652800.0  0.41  0.41  0.40  0.41
2026-09-09  12.62  12.715  11.690  11.84   775300.0  0.41  0.42  0.40  0.42
2026-09-10  11.80  12.140  11.603  11.67   657700.0  0.41  0.45  0.41  0.44
2026-09-11  11.83  12.060  11.691  11.83  1110900.0  0.43  0.47  0.42  0.44

Ticker                ...  ENGS                                BMGL        \
Price         Volume  ...  Open  High    Low Close     Volume  Open  High
Date                  ...
2025-01-02       NaN  ...   NaN   NaN    NaN   NaN        NaN   NaN   NaN
2025-01-03       NaN  ...   NaN   NaN    NaN   NaN        NaN   NaN   NaN
2025-01-06       NaN  ...   NaN   NaN    NaN   NaN        NaN   NaN   NaN
2025-01-07       NaN  ...   NaN   NaN    NaN   NaN        NaN   NaN   NaN
2025-01-08       NaN  ...   NaN   NaN    NaN   NaN        NaN   NaN   NaN
...              ...  ...   ...   ...    ...   ...        ...   ...   ...
2026-09-04   32800.0  ...  2.69  2.77  2.660  2.75  1664300.0  4.78  4.78
2026-09-08   67700.0  ...  2.76  2.87  2.750  2.82   612500.0  4.58  5.00
2026-09-09   32100.0  ...  2.81  2.94  2.800  2.89  2386700.0  4.78  4.78
2026-09-10  186400.0  ...  2.85  2.92  2.800  2.90  3290200.0  4.58  4.69
2026-09-11  138800.0  ...  2.90  2.94  2.855  2.92   593100.0  4.58  4.58

Ticker
Price        Low Close  Volume
Date
2025-01-02   NaN   NaN     NaN
2025-01-03   NaN   NaN     NaN
2025-01-06   NaN   NaN     NaN
2025-01-07   NaN   NaN     NaN
2025-01-08   NaN   NaN     NaN
...          ...   ...     ...
2026-09-04  4.78  4.78     0.0
2026-09-08  4.58  4.78  1200.0
2026-09-09  4.78  4.78     0.0
2026-09-10  4.58  4.58  2800.0
2026-09-11  4.58  4.58     0.0

[424 rows x 745 columns]

In [46]:
processed_dfs = []
for ticker in tickers:
    try:
        ticker_data = data[ticker] if len(tickers) > 1 else data
        if not ticker_data['Close'].dropna().empty:
            df = ticker_data[['Close']].copy().dropna()
            df = df.reset_index()  # Ensures 'Date' becomes an explicit column
            df['Symbol'] = ticker

            # Feature Engineering: Historical Growth & Sharpe
            df['growth_252d'] = df['Close'] / df['Close'].shift(252)
            df['volatility'] = df['Close'].rolling(30).std() * np.sqrt(252)
            df['Sharpe'] = (df['growth_252d'] - 0.05) / df['volatility']

            processed_dfs.append(df)
    except Exception:
        continue
stocks_df = pd.concat(processed_dfs,ignore_index=True)
stocks_df['Date'] = pd.to_datetime(stocks_df['Date'])
sept_11_df = stocks_df[stocks_df['Date'] == '2026-09-11']
print(f"Median Sharpe on Sep 11, 2026: {sept_11_df['Sharpe'].median():.4f}")

Median Sharpe on Sep 11, 2026: 0.0480

In [48]:
stocks_df = stocks_df.sort_values(['Symbol', 'Date']).reset_index(drop=True)

for m in range(1, 13):
    days = m * 21
    # Forward shift grouped by Symbol
    stocks_df[f'future_growth_{m}_m'] = (
        stocks_df.groupby('Symbol')['Close'].shift(-days) / stocks_df['Close']
    )

In [50]:
entry_dates = stocks_df.groupby('Symbol')['Date'].min().reset_index()
entry_dates.rename(columns={'Date': 'min_date'}, inplace=True)


ipo_entry_df = pd.merge(
    stocks_df,
    entry_dates,
    left_on=['Symbol', 'Date'],
    right_on=['Symbol', 'min_date'],
    how='inner'
)

growth_cols = [f'future_growth_{m}_m' for m in range(1, 13)]
summary_stats = ipo_entry_df[growth_cols].describe().T

summary_stats.index = [f'{m} Month(s)' for m in range(1, 13)]
print("\nPost-IPO Future Growth Statistics from Min Date")
print(summary_stats[['count', 'mean', '50%', 'std', 'min', 'max']])
peak_month = summary_stats['50%'].idxmax()
peak_median_value = summary_stats['50%'].max()
print(f"\nHighest Median Growth Month: {peak_month} (Median: {peak_median_value:.4f})")

=== Post-IPO Future Growth Statistics from Min Date ===
             count       mean       50%          std       min           max
1 Month(s)   131.0  96.475452  0.930622  1092.037636  0.072941  12500.000279
2 Month(s)   130.0  68.494523  0.891684   767.322855  0.106197   8750.000196
3 Month(s)   130.0  51.642359  0.827952   575.469311  0.090147   6562.500147
4 Month(s)   130.0  22.872042  0.736039   248.776445  0.063927   2837.500063
5 Month(s)   130.0  54.660308  0.695853   611.660280  0.032245   6975.000156
6 Month(s)   130.0  64.504145  0.733385   723.482269  0.022075   8250.000184
7 Month(s)   130.0  59.722684  0.667972   668.665749  0.013229   7625.000170
8 Month(s)   130.0  21.624139  0.603984   235.633687  0.015130   2687.500060
9 Month(s)   130.0  20.163352  0.584421   216.992585  0.014675   2475.000055
10 Month(s)  130.0  11.346041  0.533487   116.157854  0.011947   1325.000030
11 Month(s)  130.0   8.971898  0.487132    90.379471  0.008681   1031.250023
12 Month(s)  129.0   5.868163  0.508333    55.711000  0.004833    633.250012

Highest Median Growth Month: 1 Month(s) (Median: 0.9306)

In [56]:
import gdown
file_id = "1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-"
gdown.download(f"https://drive.google.com/uc?id={file_id}", "data.parquet", quiet=False)
tickers_set = pd.read_parquet("data.parquet", engine="fastparquet")
tickers_set

Downloading...
From (original): https://drive.google.com/uc?id=1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-
From (redirected): https://drive.google.com/uc?id=1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-&confirm=t&uuid=5f48e4d9-b596-4eff-aca3-462c6df8b0bb
To: /home/nyavo/Documents/ml-zoomcamp/stock-markets-analytics-zoomcamp/cohorts/2026/projects/data.parquet
100%|██████████| 130M/130M [01:02<00:00, 2.07MB/s]

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
0,0.054277,0.062259,0.054277,0.059598,1.031789e+09,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.059598,0.062791,0.059598,0.061726,3.081600e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.061726,0.063323,0.061726,0.062791,1.331712e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.062791,0.063323,0.060662,0.061194,6.776640e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.061194,0.061726,0.059598,0.060130,4.789440e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5686,3615.800049,3672.500000,3608.399902,3648.699951,1.678934e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,NaN,NaN,NaN,NaN,1.003714,1.020064,1.036306,1.156301,1.233323,1.597248
5687,3648.699951,3665.000000,3603.000000,3640.000000,2.013954e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.993181,0.989654,0.781299,0.842957,0.995927,1.011165,1.020634,1.162549,1.292217,1.570651
5688,3660.000000,3663.000000,3620.000000,3646.300049,1.293244e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.992203,1.000308,0.798376,0.886128,0.989061,0.988691,0.982898,1.135015,1.272691,1.578452
5689,3663.899902,3668.899902,3618.000000,3655.300049,1.972248e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.978792,0.991959,0.794034,0.863857,0.979958,0.965291,0.945990,1.120454,1.252080,1.563254
5690,3655.300049,3695.300049,3654.500000,3675.100098,2.571304e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.958856,0.952012,0.790642,0.818300,0.984446,0.954162,0.969342,1.103933,1.208837,1.521226

In [58]:
list(tickers_set)

['Open',
 'High',
 'Low',
 'Close_x',
 'Volume',
 'Dividends',
 'Stock Splits',
 'Ticker',
 'Year',
 'Month',
 'Weekday',
 'Date',
 'growth_1d',
 'growth_3d',
 'growth_7d',
 'growth_30d',
 'growth_90d',
 'growth_365d',
 'growth_future_30d',
 'SMA10',
 'SMA20',
 'growing_moving_average',
 'high_minus_low_relative',
 'volatility',
 'is_positive_growth_30d_future',
 'ticker_type',
 'index_x',
 'adx',
 'adxr',
 'apo',
 'aroon_1',
 'aroon_2',
 'aroonosc',
 'bop',
 'cci',
 'cmo',
 'dx',
 'macd',
 'macdsignal',
 'macdhist',
 'macd_ext',
 'macdsignal_ext',
 'macdhist_ext',
 'macd_fix',
 'macdsignal_fix',
 'macdhist_fix',
 'mfi',
 'minus_di',
 'mom',
 'plus_di',
 'dm',
 'ppo',
 'roc',
 'rocp',
 'rocr',
 'rocr100',
 'rsi',
 'slowk',
 'slowd',
 'fastk',
 'fastd',
 'fastk_rsi',
 'fastd_rsi',
 'trix',
 'ultosc',
 'willr',
 'index_y',
 'ad',
 'adosc',
 'obv',
 'atr',
 'natr',
 'ht_dcperiod',
 'ht_dcphase',
 'ht_phasor_inphase',
 'ht_phasor_quadrature',
 'ht_sine_sine',
 'ht_sine_leadsine',
 'ht_trendmod',
 'avgprice',
 'medprice',
 'typprice',
 'wclprice',
 'index',
 'cdl2crows',
 'cdl3blackrows',
 'cdl3inside',
 'cdl3linestrike',
 'cdl3outside',
 'cdl3starsinsouth',
 'cdl3whitesoldiers',
 'cdlabandonedbaby',
 'cdladvancedblock',
 'cdlbelthold',
 'cdlbreakaway',
 'cdlclosingmarubozu',
 'cdlconcealbabyswall',
 'cdlcounterattack',
 'cdldarkcloudcover',
 'cdldoji',
 'cdldojistar',
 'cdldragonflydoji',
 'cdlengulfing',
 'cdleveningdojistar',
 'cdleveningstar',
 'cdlgapsidesidewhite',
 'cdlgravestonedoji',
 'cdlhammer',
 'cdlhangingman',
 'cdlharami',
 'cdlharamicross',
 'cdlhighwave',
 'cdlhikkake',
 'cdlhikkakemod',
 'cdlhomingpigeon',
 'cdlidentical3crows',
 'cdlinneck',
 'cdlinvertedhammer',
 'cdlkicking',
 'cdlkickingbylength',
 'cdlladderbottom',
 'cdllongleggeddoji',
 'cdllongline',
 'cdlmarubozu',
 'cdlmatchinglow',
 'cdlmathold',
 'cdlmorningdojistar',
 'cdlmorningstar',
 'cdlonneck',
 'cdlpiercing',
 'cdlrickshawman',
 'cdlrisefall3methods',
 'cdlseparatinglines',
 'cdlshootingstar',
 'cdlshortline',
 'cdlspinningtop',
 'cdlstalledpattern',
 'cdlsticksandwich',
 'cdltakuru',
 'cdltasukigap',
 'cdlthrusting',
 'cdltristar',
 'cdlunique3river',
 'cdlupsidegap2crows',
 'cdlxsidegap3methods',
 'growth_dax_1d',
 'growth_dax_3d',
 'growth_dax_7d',
 'growth_dax_30d',
 'growth_dax_90d',
 'growth_dax_365d',
 'growth_snp500_1d',
 'growth_snp500_3d',
 'growth_snp500_7d',
 'growth_snp500_30d',
 'growth_snp500_90d',
 'growth_snp500_365d',
 'growth_dji_1d',
 'growth_dji_3d',
 'growth_dji_7d',
 'growth_dji_30d',
 'growth_dji_90d',
 'growth_dji_365d',
 'growth_epi_1d',
 'growth_epi_3d',
 'growth_epi_7d',
 'growth_epi_30d',
 'growth_epi_90d',
 'growth_epi_365d',
 'Quarter',
 'gdppot_us_yoy',
 'gdppot_us_qoq',
 'cpi_core_yoy',
 'cpi_core_mom',
 'FEDFUNDS',
 'DGS1',
 'DGS5',
 'DGS10',
 'Close_y',
 'growth_gold_1d',
 'growth_gold_3d',
 'growth_gold_7d',
 'growth_gold_30d',
 'growth_gold_90d',
 'growth_gold_365d',
 'growth_wti_oil_1d',
 'growth_wti_oil_3d',
 'growth_wti_oil_7d',
 'growth_wti_oil_30d',
 'growth_wti_oil_90d',
 'growth_wti_oil_365d',
 'growth_brent_oil_1d',
 'growth_brent_oil_3d',
 'growth_brent_oil_7d',
 'growth_brent_oil_30d',
 'growth_brent_oil_90d',
 'growth_brent_oil_365d',
 'growth_btc_usd_1d',
 'growth_btc_usd_3d',
 'growth_btc_usd_7d',
 'growth_btc_usd_30d',
 'growth_btc_usd_90d',
 'growth_btc_usd_365d']

In [60]:
tickers_set['is_oversold'] = tickers_set['rsi'] < 30
tickers_set.head()

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d,is_oversold
0,0.054277,0.062259,0.054277,0.059598,1.031789e+09,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,0.059598,0.062791,0.059598,0.061726,3.081600e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,0.061726,0.063323,0.061726,0.062791,1.331712e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,0.062791,0.063323,0.060662,0.061194,6.776640e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,0.061194,0.061726,0.059598,0.060130,4.789440e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [61]:
start_date = '2000-01-01'
end_date = '2025-06-01'

filtered_trades = tickers_set[
    (tickers_set['Date'] >= start_date) &
    (tickers_set['Date'] <= end_date) &
    (tickers_set['is_oversold']) &
    (tickers_set['growth_future_30d'].notna())
].copy()
filtered_trades

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d,is_oversold
3562,24.252026,24.366965,22.451323,22.719513,151217800.0,0.0,0.0,MSFT,2000,2000-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3567,20.612310,20.842187,19.922679,20.420746,313645800.0,0.0,0.0,MSFT,2000,2000-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3667,21.052906,21.072063,20.133398,20.171711,78503000.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3668,20.056772,20.114241,19.405453,19.673643,99915200.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3669,19.692798,19.807736,19.060636,19.309669,69037800.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,1472.086837,1515.287317,1445.146685,1476.416504,4328846.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.033732,1.394375,2.352383,1.008102,0.943919,0.812496,0.711329,0.693182,0.589005,True
4939,1491.330009,1508.167606,1481.179297,1484.498779,1775914.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.094358,1.413861,2.367668,0.953931,1.019800,0.985674,0.738733,0.669945,0.642821,True
5428,3286.911956,3350.660834,3241.171420,3249.902832,12120574.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.974329,1.088785,1.002989,1.030431,0.998227,1.066412,0.911930,1.337300,2.282620,True
5429,3256.005062,3280.363389,3209.371641,3245.934082,4132191.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.946388,1.090921,0.995192,0.964200,0.975262,0.966655,0.861235,1.272580,2.251519,True
5544,3425.000000,3435.000000,3315.050049,3326.399902,3236774.0,0.0,0.0,LT.NS,2024,2024-10-01,...,1.062003,0.891246,1.015218,0.977720,0.989326,0.974037,1.055418,0.982733,1.951082,True

In [64]:
INVESTMENT_PER_TRADE = 1000

filtered_trades['trade_net_income'] = INVESTMENT_PER_TRADE * (filtered_trades['growth_future_30d'] - 1.0)

net_income = filtered_trades['trade_net_income'].sum()

total_trades = len(filtered_trades)
winning_trades = (filtered_trades['trade_net_income'] > 0).sum()
win_rate = (winning_trades / total_trades) * 100 if total_trades > 0 else 0.0

print(f" Strategy Execution Summary ({start_date} to {end_date}) ")
print(f"Total Oversold Signals Executed: {total_trades:,}")
print(f"Winning Trades (> $0 profit): {winning_trades:,} ({win_rate:.2f}%)")
print(f"Average Profit per Trade: ${filtered_trades['trade_net_income'].mean():.2f}")
print(f"Net Cumulative Income: ${net_income:,.2f}")

 Strategy Execution Summary (2000-01-01 to 2025-06-01)
Total Oversold Signals Executed: 5,206
Winning Trades (> $0 profit): 2,870 (55.13%)
Average Profit per Trade: $12.64
Net Cumulative Income: $65,805.59